# Generated by Django 4.1.7 on 2023-02-23 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 23, 54, 59, 840182, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
