# Generated by Django 4.1.7 on 2023-02-23 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_update',
            new_name='update_at',
        ),
    ]
