# Generated by Django 4.1.7 on 2023-02-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_last_update_profile_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
