# Generated by Django 4.1.7 on 2023-02-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='localization',
        ),
    ]
