# Generated by Django 4.1.7 on 2023-02-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_about_profile_relationship_profile_work_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='localization',
            new_name='location',
        ),
    ]
