version: '3.1'

services:
  postgres_database:
    image: postgres:14.7
    container_name: social_media_postgres
    environment:
      POSTGRES_USER: postgres_dev_username
      POSTGRES_PASSWORD: postgres_dev_password
      POSTGRES_DB: social_media_databasename
    ports:
      - 5440:5432